import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "@/app/reset/reset.scss";
import { Header } from "@/app/components/header";
import "@/app/variables.scss";
import { Footer } from "@/app/components/footer";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

const robotoMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayoutUserPage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      style={{
        backgroundColor: "white",
        height: "100vh",
        display: "flex",
        flexDirection: "column",
      }}
      className={`${roboto.variable} ${robotoMono.variable}`}>
      <Header />
      {children}
      <Footer bgColor="black" color="white" />
    </main>
  );
}
