import { authOptions } from "@/lib/auth";
import { SessionProvideLayout } from "@/provider/sessionProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Roboto } from "next/font/google";

import "../../i18n";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

const robotoMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    "IMDx: Ratings,Reviews, and Where to Watch the best  Movies & Tv shows",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logoIMDx.png" />
      </head>
      <body className={`${roboto.variable} ${robotoMono.variable}`}>
        <SessionProvideLayout session={session}>
          {children}
        </SessionProvideLayout>
      </body>
    </html>
  );
}
