import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/reset/reset.scss";
import "@/app/variables.scss";
import "@/app/reset/reset.scss";

import { Header } from "@/app/components/header";
import { Footer } from "@/app/components/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

const robotoMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Top-Celebrities",
  description: "Generated by create next app",
};

export default function RootLayoutMovie({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${roboto.variable} ${robotoMono.variable} `}>
      <Header />
      {children}

      <Footer bgColor="black" color="white" />
    </div>
  );
}
